version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis/master/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    ports:
      - "6380:6380"
    volumes:
      - ./redis/slave1/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    ports:
      - "6381:6381"
    volumes:
      - ./redis/slave2/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
